### ISSUE TITLE
Lunch needs to focus on vetoes not on votes.

### ISSUE THREAD

**Issue by kendonaldson** [iammerrick/Lunch#3]
The problem that is being solved here is that a group of people need to decide on where to eat, not on what is their favorite.  I would recommend moving the project to allow for vetoes instead of votes.  By allowing people to down-vote restaurants, you can move the field of choices to the few places that will satisfy the most people.

**Comment by iammerrick** [comment]
I am actually agree with you.I'm wondering if a switch to a file based database makes sense... Like literally, a file we check in and write to. Removes the dependency on mongo, keeps restaurants and statistics consistent across everyones boxes. I dunno feels like a DB is overkill.

**Comment by iammerrick** [comment]
Just switch to veto verbiage, not I just need to do some categorical distribution for a selection algorithm.

**Comment by iammerrick** [comment]
Switch to vetos complete.
